/*
 * generated by Xtext
 */
package org.eclipse.emf.ecore.xcore.ui;

import org.eclipse.emf.ecore.xcore.ui.hyperlinking.XcoreHyperLinkHelper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XcoreUiModule extends org.eclipse.emf.ecore.xcore.ui.AbstractXcoreUiModule {
	public XcoreUiModule(AbstractUIPlugin plugin) 
	{
      super(plugin);
	}

	@Override
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper()
	{
	  return XcoreHyperLinkHelper.class;
	}
}
