/*
 * generated by Xtext
 */
package org.eclipse.emf.ecore.xcore.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.emf.ecore.xcore.ui.internal.XcoreActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.emf.ecore.xcore.ui.internal.XcoreActivator.getInstance().getInjector("org.eclipse.emf.ecore.xcore.Xcore");
	}
	
}
