/*
* generated by Xtext
*/
package org.eclipse.emf.ecore.xcore.ui.contentassist;

import org.eclipse.emf.ecore.xcore.ui.contentassist.AbstractXcoreProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XcoreProposalProvider extends AbstractXcoreProposalProvider {

}
