/*
* generated by Xtext
*/
package org.eclipse.emf.ecore.xcore.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class XcoreOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
